import { Injectable } from "@angular/core";
import { RandomizationConfig } from '../../../core/models/randomization.model';
import { CodeGenerationStrategy } from './base.strategy';
import { FormattingUtil } from './formatting.util';
import { ReproducibilityUtil } from './reproducibility.util';
import { APP_VERSION } from '../../../../../environments/version';
import { MethodologySpecificationService } from '../methodology-specification.service';
import { StrataParsingError, TemplateCompilationError, ConfigurationValidationError } from '../../errors/code-generation-errors';

@Injectable()
export class RStrategy implements CodeGenerationStrategy {
  readonly language = 'R';

  constructor(private methodologySpec: MethodologySpecificationService) {}

  generate(config: RandomizationConfig): string {
const generatedAt = new Date().toISOString();
    const sites = config.sites || [];
    const blockSizes = this.effectiveBlockSizes(config);
    const arms = config.arms || [];
    const strata = config.strata || [];
    const caps = config.stratumCaps || [];
    const capStrategy = config.capStrategy ?? 'MANUAL_MATRIX';

    // Branch to the marginal-only template which has entirely different generation logic.
    if (capStrategy === 'MARGINAL_ONLY') {
      this.validateMarginalOnlyConfig(config);
      return this.buildMarginalOnly(config);
    }

    // Phase 2 – Strata parsing (localized catch)
    let rCapsVector: string;
    let strataLines: string;
    let strataGridArgs: string;
    try {
      rCapsVector = caps.map(c => {
        const joinedLevels = config.strata.map(s => c.levelIds?.[s.id] || '').join('_');
        return `stats::setNames(${c.cap}, "${FormattingUtil.escapeRString(joinedLevels)}")`;
      }).join(',\n  ');
      strataLines = strata.map(s => `${s.id}_levels <- c(${(s.levels || []).map(l => '"' + FormattingUtil.escapeRString(l) + '"').join(', ')})`).join('\n');
      strataGridArgs = [...strata.map(s => `${s.id} = ${s.id}_levels`), 'stringsAsFactors = FALSE'].join(',\n  ');
    } catch (e) {
      throw new StrataParsingError('R', e, config);
    }

    // Phase 3 – Template compilation (localized catch)
    try {
      const blockStrategySection = this.buildBlockStrategySection('#', config);
      const methodologyBlock = this.methodologySpec.formatAsLineComments(
        this.methodologySpec.generateNarrative(config), '#'
      );
      return `# Randomization Schema Generation in R
# Protocol: ${config.protocolId || 'Unknown'}
# Study: ${config.studyName || 'Unknown'}
# Generated by Equipose (equipose.org)
# App Version: ${APP_VERSION}
# Generated At: ${generatedAt}
# PRNG Algorithm: Mersenne-Twister
# Source Seed Hash: ${ReproducibilityUtil.get128BitHash(config.seed)}
${this.buildCapStrategySection('#', config)}${blockStrategySection ? '\n' + blockStrategySection : ''}
${methodologyBlock}

# Set seed for reproducibility
# Note: R uses a different PRNG than the web tool, so the exact sequence will differ,
# but the statistical properties and parameters remain the same.
set.seed(${ReproducibilityUtil.hashCode(config.seed)})

# Parameters
sites <- c(${sites.map(s => '"' + s + '"').join(', ')})
block_sizes <- c(${blockSizes.join(', ')})

# Stratum Caps
stratum_caps <- c(
  ${rCapsVector}
)

# Treatment Arms
arms <- c(${arms.map(a => '"' + a.name + '"').join(', ')})
ratios <- c(${arms.map(a => a.ratio).join(', ')})
total_ratio <- sum(ratios)

# Block Math Failsafe
if (any(block_sizes %% total_ratio != 0)) {
  stop("Block sizes must be exact multiples of the total allocation ratio.")
}

# Strata
${strataLines}

# Generate all strata combinations
# stringsAsFactors=FALSE is required: expand.grid() creates factor columns by default,
# which causes paste() to emit integer level codes (1, 2, ...) instead of the actual
# label strings, breaking the stratum_caps named-vector lookup below.
strata_grid <- expand.grid(
  ${strataGridArgs}
)
# If no strata are defined, expand.grid() returns 0 rows. Insert one empty row so
# the generation loop executes once (treating the whole trial as a single stratum).
if (nrow(strata_grid) == 0) strata_grid <- data.frame(row.names = 1L)

# Function to generate a single block
generate_block <- function(block_size) {
  multiplier <- block_size / total_ratio
  block <- rep(arms, times = ratios * multiplier)
  sample(block) # Shuffle
}

# Generate Schema
schema_list <- list()
row_idx <- 1

for (site in sites) {
  site_subject_count <- 0
  # seq_len() is used instead of 1:nrow() to avoid the R gotcha where 1:0 produces
  # c(1, 0) instead of an empty sequence when there are no rows.
  for (i in seq_len(nrow(strata_grid))) {
    stratum <- strata_grid[i, , drop=FALSE]
    # In the unstratified case, expand.grid() produces a 1-row, 0-column data.frame.
    # Force a scalar empty key so the stratum_caps named-vector lookup remains length-1.
    if (ncol(stratum) == 0) {
      stratum_key <- ""
    } else {
      # unlist() is required to coerce the data.frame row to a plain character vector
      # before pasting; directly pasting a data.frame can give unexpected results.
      stratum_key <- paste(unlist(stratum), collapse="_")
      if (length(stratum_key) == 0) stratum_key <- ""
    }
    max_subjects_per_stratum <- if (length(stratum_caps) > 0) unname(stratum_caps[stratum_key]) else 0
    if (is.na(max_subjects_per_stratum)) max_subjects_per_stratum <- 0

    stratum_subject_count <- 0
    block_number <- 1

    while (stratum_subject_count < max_subjects_per_stratum) {
      # Pick random block size
      current_block_size <- sample(block_sizes, 1)

      # Generate block
      current_block <- generate_block(current_block_size)

      for (treatment in current_block) {
        site_subject_count <- site_subject_count + 1
        stratum_subject_count <- stratum_subject_count + 1

        # Format Subject ID (Simplified)
        subject_id <- sprintf("%s-%03d", site, site_subject_count)

        row <- data.frame(
          SubjectID = subject_id,
          Site = site,
          BlockNumber = block_number,
          BlockSize = current_block_size,
          Treatment = treatment
        )
        row <- cbind(row, stratum)

        schema_list[[row_idx]] <- row
        row_idx <- row_idx + 1

        if (stratum_subject_count >= max_subjects_per_stratum) break
      }
      if (stratum_subject_count >= max_subjects_per_stratum) break
      block_number <- block_number + 1
    }
  }
}

schema <- do.call(rbind, schema_list)

# Guard: when no subjects were generated (e.g. all caps are 0 or sites is empty),
# do.call(rbind, list()) returns NULL. Create an empty typed data.frame so that
# downstream code (print, write.csv) does not error.
if (is.null(schema) || nrow(schema) == 0) {
  base_schema <- data.frame(
    SubjectID = character(0),
    Site = character(0),
    BlockNumber = integer(0),
    BlockSize = integer(0),
    Treatment = character(0)
  )
  schema <- cbind(base_schema, strata_grid[0, , drop=FALSE])
}
print(utils::head(schema))

if (nrow(schema) > 0) {
  cat("\\n--- QC Check: Overall Allocation ---\\n")
  print(table(schema$Treatment))

  cat("\\n--- QC Check: Site-Level Balance ---\\n")
  print(table(schema$Site, schema$Treatment))

  cat("\\n--- QC Check: Dynamic Block Utilization ---\\n")
  print(table(schema$BlockSize))
} else {
  cat("\\n--- QC Check ---\\n")
  cat("No rows generated; skipping QC tables.\\n")
}

# write.csv(schema, "randomization_schema.csv", row.names=FALSE)
`;
    } catch (e) {
      if (this.isKnownError(e)) throw e;
      throw new TemplateCompilationError('R', e, config);
    }
  }

  generateMinimization(config: RandomizationConfig): string {
const sites = config.sites || [];
    const arms = config.arms || [];
    const strata = config.strata || [];
    const mc = config.minimizationConfig;
    const p = mc?.p ?? 0.8;
    const n = mc?.totalSampleSize ?? 100;
    const isMarginal = config.capStrategy === 'MARGINAL_ONLY';

    const header = this.generateMinimizationHeader('R', config);

    let setupCode: string;
    let capsCode: string;
    let strataLines: string;
    let baseProbsCode: string;

    try {
      strataLines = strata.map(s => `${s.id}_levels <- c(${(s.levels || []).map(l => '"' + FormattingUtil.escapeRString(l) + '"').join(', ')})`).join('\n');

      if (isMarginal) {
        const marginalCaps = strata.map(s => {
          const entries = s.levels.map((lvl, i) => {
            const cap = s.levelDetails?.[i]?.marginalCap;
            return cap !== undefined ? `"${FormattingUtil.escapeRString(lvl)}" = ${cap}` : `"${FormattingUtil.escapeRString(lvl)}" = Inf`;
          });
          return `  ${s.id} = c(${entries.join(', ')})`;
        }).join(',\n');
        capsCode = `marginal_caps <- list(\n${marginalCaps}\n)\n\n` +
                   `marginal_counts <- list(\n` +
                   strata.map(s => `  ${s.id} = stats::setNames(rep(0, ${s.levels.length}), ${s.id}_levels)`).join(',\n') +
                   `\n)`;
      } else {
        const caps = config.stratumCaps || [];
        const capsVector = caps
          .map(c => {
            const levelsStr = strata.map(s => c.levelIds?.[s.id] ?? '').join('_');
            return `stats::setNames(${c.cap}, "${FormattingUtil.escapeRString(levelsStr)}")`;
          })
          .join(',\n  ');
        capsCode = `stratum_caps <- c(\n  ${capsVector}\n)\nintersection_counts <- list()`;
      }

      baseProbsCode = `base_probs <- list(\n` + strata.map(s => {
        const probs = s.levels.map((lvl, i) => {
          const expected = s.levelDetails?.[i]?.expectedProbability;
          return expected !== undefined ? expected : 'NA';
        });
        return `  ${s.id} = c(${probs.join(', ')})`;
      }).join(',\n') + `\n)`;

      const strataGridArgs = [...strata.map(s => `${s.id} = ${s.id}_levels`), 'stringsAsFactors = FALSE'].join(',\n  ');
      setupCode = `
# Strata
${strataLines}

strata_grid <- expand.grid(
  ${strataGridArgs}
)
if (nrow(strata_grid) == 0) strata_grid <- data.frame(row.names = 1L)

# Expected Probabilities
${baseProbsCode}

# Caps and Counts
${capsCode}

# Treatment Arms
arms <- c(${arms.map(a => '"' + a.id + '"').join(', ')})
arm_names <- c(${arms.map(a => '"' + a.name + '"').join(', ')})
ratios <- c(${arms.map(a => a.ratio).join(', ')})
total_ratio <- sum(ratios)
names(ratios) <- arms
names(arm_names) <- arms

# Imbalance Tracking (Global)
marginal_imbalance <- list()
for (factor_id in names(strata_grid)) {
  levels <- get(paste0(factor_id, "_levels"))
  marginal_imbalance[[factor_id]] <- list()
  for (lvl in levels) {
    marginal_imbalance[[factor_id]][[lvl]] <- stats::setNames(rep(0, length(arms)), arms)
  }
}
`;
    } catch (e) {
      throw new StrataParsingError('R', e, config);
    }

    try {
      return `${header}
# Note: R's set.seed() algorithm will not generate the exact same sequence as the
# typescript web application, but the statistical properties and parameters are identical.

set.seed(${ReproducibilityUtil.hashCode(config.seed)})

# Parameters
p_minimization <- ${p}
total_sample_size <- ${n}
sites <- c(${sites.map(s => '"' + s + '"').join(', ')})
if (length(sites) == 0) stop("Sites array is empty.")
${setupCode}

# Setup site counts
site_subject_counts <- stats::setNames(rep(0, length(sites)), sites)
schema_list <- list()
row_idx <- 1
used_subject_ids <- character(0)

# Function to generate Subject ID
generate_subject_id <- function(mask, site, stratum_code, sequence) {
  # Simple translation of Subject ID generation for this generated code
  id <- sprintf("%s-%03d", site, sequence)
  # Basic loop to ensure uniqueness
  while (id %in% used_subject_ids) {
     sequence <- sequence + 1
     id <- sprintf("%s-%03d", site, sequence)
  }
  used_subject_ids <<- c(used_subject_ids, id)
  return(id)
}

sample_level <- function(available_levels, probs_vector) {
  if (length(available_levels) == 0) stop("Cannot sample from empty levels.")

  if (all(is.na(probs_vector))) {
     return(sample(available_levels, 1))
  }

  explicit_sum <- sum(probs_vector[!is.na(probs_vector)], na.rm = TRUE)

  probs <- numeric(length(probs_vector))
  if (explicit_sum > 1.0) {
    probs <- ifelse(is.na(probs_vector), 0, probs_vector / explicit_sum)
  } else if (explicit_sum == 1.0) {
    probs <- ifelse(is.na(probs_vector), 0, probs_vector)
  } else if (explicit_sum > 0 && explicit_sum < 1.0) {
    na_count <- sum(is.na(probs_vector))
    if (na_count > 0) {
      share <- (1.0 - explicit_sum) / na_count
      probs <- ifelse(is.na(probs_vector), share, probs_vector)
    } else {
      probs <- ifelse(is.na(probs_vector), 0, probs_vector / explicit_sum)
    }
  } else {
    probs <- rep(1 / length(probs_vector), length(probs_vector))
  }

  return(sample(available_levels, 1, prob = probs))
}

compute_imbalance_score <- function(candidate_arm_id, profile, marginals) {
  total_score <- 0
  for (factor_id in names(profile)) {
    level_value <- as.character(profile[[factor_id]])
    arm_counts <- marginals[[factor_id]][[level_value]]

    arm_counts[candidate_arm_id] <- arm_counts[candidate_arm_id] + 1

    min_val <- Inf
    max_val <- -Inf
    for (arm in arms) {
      normalized <- arm_counts[arm] / ratios[arm]
      if (normalized < min_val) min_val <- normalized
      if (normalized > max_val) max_val <- normalized
    }
    total_score <- total_score + (max_val - min_val)
  }
  return(total_score)
}

active_pool <- strata_grid

for (s_idx in 1:total_sample_size) {
  # Update active pool
${isMarginal ? `
  keep_flags <- sapply(1:nrow(active_pool), function(i) {
    combo_row <- active_pool[i, , drop = FALSE]
    all(sapply(names(marginal_caps), function(factor_id) {
      level_val <- as.character(combo_row[[factor_id]])
      cap_val <- marginal_caps[[factor_id]][[level_val]]
      count <- marginal_counts[[factor_id]][[level_val]]
      is.infinite(cap_val) || count < cap_val
    }))
  })
` : `
  keep_flags <- sapply(1:nrow(active_pool), function(i) {
    combo_row <- active_pool[i, , drop = FALSE]
    key <- if (ncol(combo_row) == 0) "" else paste(unlist(combo_row), collapse="_")
    cap <- if (key %in% names(stratum_caps)) stratum_caps[[key]] else Inf
    count <- if (is.null(intersection_counts[[key]])) 0 else intersection_counts[[key]]
    is.infinite(cap) || count < cap
  })
`}
  active_pool <- active_pool[keep_flags, , drop = FALSE]

  if (nrow(active_pool) == 0) {
    break # Exhaustion
  }

  site <- sample(sites, 1)

  subject_profile <- list()
  stratum <- list()
  current_prefix <- list()
  valid_subject <- TRUE

  for (factor_id in names(strata_grid)) {
    levels <- get(paste0(factor_id, "_levels"))
    available_levels <- character(0)
    for (lvl in levels) {
      match_idx <- sapply(1:nrow(active_pool), function(i) {
        combo <- active_pool[i, , drop = FALSE]
        match_prefix <- TRUE
        for (k in names(current_prefix)) {
           if (combo[[k]] != current_prefix[[k]]) match_prefix <- FALSE
        }
        return(match_prefix && combo[[factor_id]] == lvl)
      })
      if (any(match_idx)) {
         available_levels <- c(available_levels, lvl)
      }
    }

    if (length(available_levels) == 0) {
      valid_subject <- FALSE
      break
    }

    prob_indices <- match(available_levels, levels)
    probs_vector <- base_probs[[factor_id]][prob_indices]

    level <- sample_level(available_levels, probs_vector)
    subject_profile[[factor_id]] <- level
    stratum[[factor_id]] <- level
    current_prefix[[factor_id]] <- level
  }

  if (!valid_subject) break

  # Imbalance Score per site. (Using global marginal tracking)
  min_score <- Inf
  arm_scores <- numeric(length(arms))
  for (j in seq_along(arms)) {
    score <- compute_imbalance_score(arms[j], subject_profile, marginal_imbalance)
    arm_scores[j] <- score
    if (score < min_score) min_score <- score
  }

  preferred <- arms[arm_scores == min_score]
  non_preferred <- arms[arm_scores != min_score]

  assigned_arm_id <- NA
  if (length(preferred) == length(arms) || length(non_preferred) == 0) {
    assigned_arm_id <- sample(preferred, 1, prob = ratios[preferred] / sum(ratios[preferred]))
  } else {
    if (stats::runif(1) < p_minimization) {
      assigned_arm_id <- sample(preferred, 1, prob = ratios[preferred] / sum(ratios[preferred]))
    } else {
      assigned_arm_id <- sample(non_preferred, 1, prob = ratios[non_preferred] / sum(ratios[non_preferred]))
    }
  }

  # Update state
  for (factor_id in names(subject_profile)) {
    lvl <- subject_profile[[factor_id]]
    marginal_imbalance[[factor_id]][[lvl]][assigned_arm_id] <- marginal_imbalance[[factor_id]][[lvl]][assigned_arm_id] + 1
${isMarginal ? `
    marginal_counts[[factor_id]][[lvl]] <- marginal_counts[[factor_id]][[lvl]] + 1
` : ''}
  }

${!isMarginal ? `
  key <- paste(unlist(subject_profile), collapse="_")
  if (is.null(intersection_counts[[key]])) {
    intersection_counts[[key]] <- 1
  } else {
    intersection_counts[[key]] <- intersection_counts[[key]] + 1
  }
` : ''}

  site_subject_counts[site] <- site_subject_counts[site] + 1
  stratum_code <- paste(sapply(stratum, function(v) toupper(substr(v, 1, 3))), collapse="-")
  subject_id <- generate_subject_id("MASK", site, stratum_code, site_subject_counts[site])

  row <- data.frame(
    SubjectID = subject_id,
    Site = site,
    BlockNumber = 0,
    BlockSize = 0,
    Treatment = arm_names[assigned_arm_id],
    TreatmentId = assigned_arm_id,
    stringsAsFactors = FALSE
  )
  row <- cbind(row, as.data.frame(stratum, stringsAsFactors = FALSE))
  schema_list[[row_idx]] <- row
  row_idx <- row_idx + 1
}

schema <- do.call(rbind, schema_list)
if (is.null(schema) || nrow(schema) == 0) {
  base_schema <- data.frame(
    SubjectID = character(0),
    Site = character(0),
    BlockNumber = integer(0),
    BlockSize = integer(0),
    Treatment = character(0),
    TreatmentId = character(0)
  )
  schema <- cbind(base_schema, strata_grid[0, , drop = FALSE])
}

print(utils::head(schema))

if (nrow(schema) > 0) {
  cat("\\n--- QC Check: Overall Allocation ---\\n")
  print(table(schema$Treatment))

  cat("\\n--- QC Check: Site-Level Balance ---\\n")
  print(table(schema$Site, schema$Treatment))
} else {
  cat("\\n--- QC Check ---\\n")
  cat("No rows generated; skipping QC tables.\\n")
}
`;
    } catch (e) {
      if (this.isKnownError(e)) throw e;
      throw new TemplateCompilationError('R', e, config);
    }
  }

  private isKnownError(e: unknown): boolean {
    return e instanceof StrataParsingError || e instanceof ConfigurationValidationError;
  }


  private buildMarginalOnly(config: RandomizationConfig): string {
const generatedAt = new Date().toISOString();
    const sites = config.sites || [];
    const blockSizes = this.effectiveBlockSizes(config);
    const arms = config.arms || [];
    const strata = config.strata || [];

    let rMarginalCaps: string;
    let strataLines: string;
    let strataGridArgs: string;
    try {
      rMarginalCaps = strata.map(s => {
        const entries = s.levels.map((lvl, i) => {
          const cap = s.levelDetails?.[i]?.marginalCap;
          return cap !== undefined ? `"${FormattingUtil.escapeRString(lvl)}" = ${cap}` : null;
        }).filter(Boolean);
        return `  ${s.id} = list(${entries.join(', ')})`;
      }).join(',\n');
      strataLines = strata.map(s =>
        `${s.id}_levels <- c(${s.levels.map(l => '"' + FormattingUtil.escapeRString(l) + '"').join(', ')})`
      ).join('\n');
      strataGridArgs = [...strata.map(s => `${s.id} = ${s.id}_levels`), 'stringsAsFactors = FALSE'].join(',\n  ');
    } catch (e) {
      throw new StrataParsingError('R', e, config);
    }

    try {
      const blockStrategySection = this.buildBlockStrategySection('#', config);
      const methodologyBlock = this.methodologySpec.formatAsLineComments(
        this.methodologySpec.generateNarrative(config), '#'
      );
      return `# Randomization Schema Generation in R
# Protocol: ${config.protocolId || 'Unknown'}
# Study: ${config.studyName || 'Unknown'}
# Generated by Equipose (equipose.org)
# App Version: ${APP_VERSION}
# Generated At: ${generatedAt}
# PRNG Algorithm: Mersenne-Twister
# Source Seed Hash: ${ReproducibilityUtil.get128BitHash(config.seed)}
${this.buildCapStrategySection('#', config)}${blockStrategySection ? '\n' + blockStrategySection : ''}
${methodologyBlock}
# Subjects are allocated by randomly selecting valid stratum combinations
# until no combination can accept additional subjects.

# Set seed for reproducibility
set.seed(${ReproducibilityUtil.hashCode(config.seed)})

# Parameters
sites <- c(${sites.map(s => '"' + s + '"').join(', ')})
block_sizes <- c(${blockSizes.join(', ')})

# Treatment Arms
arms <- c(${arms.map(a => '"' + a.name + '"').join(', ')})
ratios <- c(${arms.map(a => a.ratio).join(', ')})
total_ratio <- sum(ratios)

# Block Math Failsafe
if (any(block_sizes %% total_ratio != 0)) {
  stop("Block sizes must be exact multiples of the total allocation ratio.")
}

# Strata
${strataLines}

strata_grid <- expand.grid(
  ${strataGridArgs}
)
if (nrow(strata_grid) == 0) strata_grid <- data.frame(row.names = 1L)

# Marginal Caps (per factor, per level; NULL = uncapped)
marginal_caps <- list(
${rMarginalCaps}
)

# Function to generate a single block
generate_block <- function(block_size) {
  multiplier <- block_size / total_ratio
  block <- rep(arms, times = ratios * multiplier)
  sample(block) # Shuffle
}

# Generate Schema with Marginal Cap Enforcement
schema_list <- list()
row_idx <- 1

for (site in sites) {
  site_subject_count <- 0L
  block_number <- 0L

  # Per-factor, per-level enrollment counts (reset for each site)
  marginal_counts <- lapply(marginal_caps, function(mc) {
    stats::setNames(rep(0L, length(mc)), names(mc))
  })

  # Active pool of strata combinations (those not yet exhausted)
  active_pool <- strata_grid

  while (nrow(active_pool) > 0) {
    # Randomly select a combination from the active pool
    pool_idx <- sample(nrow(active_pool), 1)
    stratum  <- active_pool[pool_idx, , drop = FALSE]

    # Pick a random block size and generate the block
    current_block_size <- sample(block_sizes, 1)
    current_block <- generate_block(current_block_size)
    block_number <- block_number + 1L

    for (treatment in current_block) {
      # Check marginal caps before enrolling this subject
      can_add <- TRUE
      for (factor_id in names(marginal_caps)) {
        level_val <- as.character(stratum[[factor_id]])
        cap_val   <- marginal_caps[[factor_id]][[level_val]]
        if (!is.null(cap_val) && marginal_counts[[factor_id]][[level_val]] >= cap_val) {
          can_add <- FALSE
          break
        }
      }
      if (!can_add) break

      site_subject_count <- site_subject_count + 1L
      subject_id <- sprintf("%s-%03d", site, site_subject_count)

      row <- data.frame(
        SubjectID   = subject_id,
        Site        = site,
        BlockNumber = block_number,
        BlockSize   = current_block_size,
        Treatment   = treatment
      )
      row <- cbind(row, stratum)
      schema_list[[row_idx]] <- row
      row_idx <- row_idx + 1L

      # Update marginal counts
      for (factor_id in names(marginal_caps)) {
        level_val <- as.character(stratum[[factor_id]])
        if (!is.null(marginal_caps[[factor_id]][[level_val]])) {
          marginal_counts[[factor_id]][[level_val]] <-
            marginal_counts[[factor_id]][[level_val]] + 1L
        }
      }
    }

    # Prune pool: remove combinations that breach any marginal cap
    keep_flags <- sapply(seq_len(nrow(active_pool)), function(i) {
      combo_row <- active_pool[i, , drop = FALSE]
      all(sapply(names(marginal_caps), function(factor_id) {
        level_val <- as.character(combo_row[[factor_id]])
        cap_val   <- marginal_caps[[factor_id]][[level_val]]
        is.null(cap_val) || marginal_counts[[factor_id]][[level_val]] < cap_val
      }))
    })
    active_pool <- active_pool[keep_flags, , drop = FALSE]
  }
}

schema <- do.call(rbind, schema_list)
if (is.null(schema) || nrow(schema) == 0) {
  base_schema <- data.frame(
    SubjectID   = character(0),
    Site        = character(0),
    BlockNumber = integer(0),
    BlockSize   = integer(0),
    Treatment   = character(0)
  )
  schema <- cbind(base_schema, strata_grid[0, , drop = FALSE])
}
print(utils::head(schema))

if (nrow(schema) > 0) {
  cat("\\n--- QC Check: Overall Allocation ---\\n")
  print(table(schema$Treatment))

  cat("\\n--- QC Check: Site-Level Balance ---\\n")
  print(table(schema$Site, schema$Treatment))

  cat("\\n--- QC Check: Dynamic Block Utilization ---\\n")
  print(table(schema$BlockSize))
} else {
  cat("\\n--- QC Check ---\\n")
  cat("No rows generated; skipping QC tables.\\n")
}

# write.csv(schema, "randomization_schema.csv", row.names=FALSE)
`;
    } catch (e) {
      if (this.isKnownError(e)) throw e;
      throw new TemplateCompilationError('R', e, config);
    }
  }



  private generateMinimizationHeader(language: string, config: RandomizationConfig): string {
const generatedAt = new Date().toISOString();
const arms = config.arms || [];
const strata = config.strata || [];
const mc = config.minimizationConfig;
const p = mc?.p ?? 0.8;
const n = mc?.totalSampleSize ?? 100;

const armLines = arms.map(a => `  ${a.name} (ratio: ${a.ratio})`).join('\n');
const strataLines = strata.map(s => {
  const levels = s.levelDetails?.length
    ? s.levels.map(lvl => {
        const detail = s.levelDetails!.find(d => d.name === lvl);
        const prob = detail?.expectedProbability !== undefined
          ? ` (p=${(detail.expectedProbability * 100).toFixed(1)}%)`
          : '';
        return `    - ${lvl}${prob}`;
      }).join('\n')
    : s.levels.map(lvl => `    - ${lvl}`).join('\n');
  return `  ${s.name || s.id}:\n${levels}`;
}).join('\n');

const body = [
  `Randomization Schema Configuration`,
  `Protocol: ${config.protocolId || 'Unknown'}`,
  `Study: ${config.studyName || 'Unknown'}`,
  `Generated by Equipose (equipose.org)`,
  `App Version: ${APP_VERSION}`,
  `Generated At: ${generatedAt}`,
  ``,
  `Algorithm: Pocock-Simon Minimization`,
  `Source Seed Hash: ${ReproducibilityUtil.get128BitHash(config.seed)}`,
  `Base Probability (p): ${p}`,
  `Total Sample Size (N): ${n}`,
  `Sites: ${(config.sites || []).join(', ')}`,
  ``,
  `Treatment Arms:`,
  armLines,
  ``,
  `Stratification Factors:`,
  strataLines,
  ``,
  `NOTE: The Pocock-Simon minimization algorithm dynamically assigns treatments`,
  `to minimise marginal imbalance across all stratification factors.`,
  `Full implementation in ${language} requires a custom sequential allocation loop.`,
  `The schema generated by the application (CSV export) is the authoritative`,
  `randomisation list and should be used directly in trial operations.`,
].join('\n');

if (language === 'SAS') {
  return body.split('\n').map(l => `/* ${l} */`).join('\n');
}
const prefix = language === 'STATA' ? '* ' : '# ';
return body.split('\n').map(l => `${prefix}${l}`).join('\n');
  }


  private effectiveBlockSizes(config: RandomizationConfig): number[] {
    return config.globalBlockStrategy?.sizes ?? config.blockSizes ?? [];
  }

  private buildBlockStrategySection(prefix: string, config: RandomizationConfig): string {
    const lines: string[] = [];
    const strategy = config.globalBlockStrategy;
    if (strategy) {
      lines.push(`${prefix} Block Selection Mode: ${strategy.selectionType}`);
      if (strategy.selectionType === 'FIXED_SEQUENCE') {
        lines.push(`${prefix} Sizes are applied in order and cycle when exhausted.`);
      }
      if (strategy.limits && Object.keys(strategy.limits).length) {
        const limitStr = Object.entries(strategy.limits).map(([k, v]) => `${k}→max ${v}`).join(', ');
        lines.push(`${prefix} Usage limits: ${limitStr}`);
      }
    }
    if (config.siteBlockOverrides && Object.keys(config.siteBlockOverrides).length) {
      lines.push(`${prefix} Site-level block overrides defined for: ${Object.keys(config.siteBlockOverrides).join(', ')}`);
      lines.push(`${prefix} NOTE: Site-specific overrides are not replicated in this generated code.`);
      lines.push(`${prefix}       Apply the override logic manually for the affected sites.`);
    }
    if (config.stratumBlockOverrides && Object.keys(config.stratumBlockOverrides).length) {
      lines.push(`${prefix} Stratum-level block overrides defined for: ${Object.keys(config.stratumBlockOverrides).join(', ')}`);
      lines.push(`${prefix} NOTE: Stratum-specific overrides are not replicated in this generated code.`);
      lines.push(`${prefix}       Apply the override logic manually for the affected strata.`);
    }
    return lines.length ? lines.join('\n') : '';
  }

  private buildCapStrategySection(prefix: string, config: RandomizationConfig): string {
    const strategy = config.capStrategy ?? 'MANUAL_MATRIX';
    const lines: string[] = [];
    if (strategy === 'PROPORTIONAL') {
      lines.push(`${prefix} Cap Strategy: PROPORTIONAL (Largest Remainder Method)`);
      if (config.globalCap !== undefined) {
        lines.push(`${prefix} Global Enrollment Cap (per site): ${config.globalCap}`);
      }
      for (const s of (config.strata || [])) {
        const detailByName = new Map((s.levelDetails ?? []).map(d => [d.name, d]));
        const lvlPcts = s.levels.map(lvl => {
          const pct = detailByName.get(lvl)?.targetPercentage;
          return pct !== undefined ? `${lvl}=${pct}%` : null;
        }).filter(Boolean);
        if (lvlPcts.length) {
          lines.push(`${prefix} ${s.name}: ${lvlPcts.join(', ')}`);
        }
      }
      lines.push(`${prefix} Intersection caps below were LRM-computed from the above percentages.`);
    } else if (strategy === 'MARGINAL_ONLY') {
      lines.push(`${prefix} Cap Strategy: MARGINAL_ONLY`);
      lines.push(`${prefix} Per-factor, per-level caps; no intersection caps needed.`);
    } else {
      lines.push(`${prefix} Cap Strategy: MANUAL_MATRIX`);
      lines.push(`${prefix} Intersection caps are defined explicitly.`);
    }
    return lines.join('\n');
  }

  private validateMarginalOnlyConfig(config: RandomizationConfig): void {
    const hasFullyCappedFactor = (config.strata || []).some(s => {
      if (!s.levels || s.levels.length === 0) return false;
      const detailByName = new Map((s.levelDetails ?? []).map(d => [d.name, d]));
      return s.levels.every(lvl => {
        const detail = detailByName.get(lvl);
        return detail !== undefined && Number.isFinite(detail.marginalCap);
      });
    });
    if (!hasFullyCappedFactor) {
      throw new ConfigurationValidationError(
        'MARGINAL_ONLY cap strategy requires at least one stratification factor to define a finite ' +
        'marginalCap for every level, so every stratum combination can be deactivated and the ' +
        'active-pool loop can terminate.',
        config
      );
    }
  }

  private computeCombinations(strata: any[]): Record<string, string>[] {
    let combos = [{}];
    for (const s of strata) {
      const next = [];
      for (const combo of combos) {
        for (const lvl of s.levels) {
          next.push({ ...combo, [s.id]: lvl });
        }
      }
      combos = next;
    }
    return combos.length ? combos : [{}];
  }
}
